### ISSUE TITLE
Version compatibility problem with DCN and Detectron2

### ISSUE THREAD

**Issue by Shawn207** [Picsart-AI-Research/SeMask-Segmentation#22]
Hi there!
According to your setup instruction for SeMask-FaPN, building DCNv2 with torch 1.7.1, following installing Detectron 2 is needed. However, Detectron2 documents requires torch >= 1.8. I upgraded torch to 1.8.0 but DCNv2 gives the following error:
`(SeMask) xzhan2@cerlab27:~/SeMask-Segmentation/SeMask-FAPN/SeMask-Mask2Former/demo$ python demo.py --config-file ../configs/ade20k/semantic-segmentation/semask_swin/fapn_maskformer2_semask_swin_large_IN21k_384_bs16_160k_res640.yaml   --input ~/Pictures/test.jpeg
Traceback (most recent call last):
  File "demo.py", line 26, in <module>
    from mask2former import add_maskformer2_config
  File "/home/xzhan2/SeMask-Segmentation/SeMask-FAPN/SeMask-Mask2Former/demo/../mask2former/__init__.py", line 3, in <module>
    from . import modeling
  File "/home/xzhan2/SeMask-Segmentation/SeMask-FAPN/SeMask-Mask2Former/demo/../mask2former/modeling/__init__.py", line 5, in <module>
    from .pixel_decoder.fapn import PixelFANDecoder
  File "/home/xzhan2/SeMask-Segmentation/SeMask-FAPN/SeMask-Mask2Former/demo/../mask2former/modeling/pixel_decoder/fapn.py", line 16, in <module>
    from dcn_v2 import DCN as dcn_v2
  File "/home/xzhan2/SeMask-Segmentation/SeMask-FAPN/DCNv2/dcn_v2.py", line 17, in <module>
    import _ext as _backend
ImportError: /home/xzhan2/SeMask-Segmentation/SeMask-FAPN/DCNv2/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv`

I also tried to degrade to torch 1.7 and install Detectron with torch 1.7, but it fails. The version requriements seem to be conflicting. Could you please give me a bit suggestions?
Thanks a lot!!

**Comment by praeclarumjj3** [comment]
Hi, thanks for your interest in our work. Have you tried installing v0.5 for Detectron2?
https://github.com/facebookresearch/detectron2/releases

**Comment by Shawn207** [comment]
> Hi, thanks for your interest in our work. Have you tried installing v0.5 for Detectron2? https://github.com/facebookresearch/detectron2/releases

Thanks for your suggestion. It seems reasonable but one more question: my current cuda version is 11.2, but non of these versions includes that for 11.2. Does it matter?

**Comment by Shawn207** [comment]
Actually I tried v0.5. It seems worked but getting another error:
`Traceback (most recent call last):
  File "demo.py", line 26, in <module>
    from mask2former import add_maskformer2_config
  File "/home/xzhan2/SeMask-Segmentation/SeMask-FAPN/SeMask-Mask2Former/demo/../mask2former/__init__.py", line 3, in <module>
    from . import modeling
  File "/home/xzhan2/SeMask-Segmentation/SeMask-FAPN/SeMask-Mask2Former/demo/../mask2former/modeling/__init__.py", line 6, in <module>
    from .pixel_decoder.msdeformattn import MSDeformAttnPixelDecoder
  File "/home/xzhan2/SeMask-Segmentation/SeMask-FAPN/SeMask-Mask2Former/demo/../mask2former/modeling/pixel_decoder/msdeformattn.py", line 20, in <module>
    from .ops.modules import MSDeformAttn
  File "/home/xzhan2/SeMask-Segmentation/SeMask-FAPN/SeMask-Mask2Former/demo/../mask2former/modeling/pixel_decoder/ops/modules/__init__.py", line 12, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/home/xzhan2/SeMask-Segmentation/SeMask-FAPN/SeMask-Mask2Former/demo/../mask2former/modeling/pixel_decoder/ops/modules/ms_deform_attn.py", line 24, in <module>
    from ..functions import MSDeformAttnFunction
  File "/home/xzhan2/SeMask-Segmentation/SeMask-FAPN/SeMask-Mask2Former/demo/../mask2former/modeling/pixel_decoder/ops/functions/__init__.py", line 12, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "/home/xzhan2/SeMask-Segmentation/SeMask-FAPN/SeMask-Mask2Former/demo/../mask2former/modeling/pixel_decoder/ops/functions/ms_deform_attn_func.py", line 22, in <module>
    import MultiScaleDeformableAttention as MSDA
ImportError: /home/xzhan2/anaconda3/envs/SeMask/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20getCurrentCUDAStreamEa`
I am suspecting that's because of CUDA version imcompatibility?

**Comment by Shawn207** [comment]
Nevermind. Solved by running cuda 11.0 pytorch 1.7.1 docker. Thank you!
